# Generated by Django 5.1.7 on 2025-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
